version: "3.7"
services:
  pwa-dev:
    container_name: pwa-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./:/pwa"
      - "./node_modules:/pwa/node_modules"
    environment:
      - NODE_ENV=development