FROM node:alpine as build
WORKDIR /pwa
COPY . /pwa
ENV PATH /pwa/node_modules/.bin:$PATH
# install and cache dependencies
RUN yarn
RUN yarn build
FROM nginx:alpine
COPY --from=build /pwa/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]