version: '3.7'

services:
    nginx_pwa_hacka:
        image: nginx:latest
        container_name: nginx_pwa_hacka
        volumes:
          - ./build:/var/www/html
          - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
        ports:
          - 7777:80
    pm2_pwa_hacka:
        build: .
        container_name: pm2_pwa_hacka
        volumes:
            - ./node_modules:/home/node/node_modules
            - ./server:/home/node/server