export default {
  SHOW_AUTH_MODAL: 'SHOW_AUTH_MODAL',
  HIDE_AUTH_MODAL: 'HIDE_AUTH_MODAL',
  SET_FORCE_AUTH_MODAL: 'SET_FORCE_AUTH_MODAL',

  // will get user login message code
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // send token to login
  LOGIN_MOBILE_WITH_TOKEN_REQUEST: 'LOGIN_MOBILE_WITH_TOKEN_REQUEST',
  LOGIN_MOBILE_WITH_TOKEN_SUCCESS: 'LOGIN_MOBILE_WITH_TOKEN_SUCCESS',
  LOGIN_MOBILE_WITH_TOKEN_FAILURE: 'LOGIN_MOBILE_WITH_TOKEN_FAILURE',

  // to submit user register with code
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};
