export default {
  SHOW_AUTH_MODAL: 'SHOW_AUTH_MODAL',
  HIDE_AUTH_MODAL: 'HIDE_AUTH_MODAL',
  SET_FORCE_AUTH_MODAL: 'SET_FORCE_AUTH_MODAL',

  // will get user login message code
  LOGIN_WITH_NO_PASS_REQUEST: 'LOGIN_WITH_NO_PASS_REQUEST',
  LOGIN_WITH_NO_PASS_SUCCESS: 'LOGIN_WITH_NO_PASS_SUCCESS',
  LOGIN_WITH_NO_PASS_FAILURE: 'LOGIN_WITH_NO_PASS_FAILURE',

  // send token to login
  LOGIN_MOBILE_WITH_TOKEN_REQUEST: 'LOGIN_MOBILE_WITH_TOKEN_REQUEST',
  LOGIN_MOBILE_WITH_TOKEN_SUCCESS: 'LOGIN_MOBILE_WITH_TOKEN_SUCCESS',
  LOGIN_MOBILE_WITH_TOKEN_FAILURE: 'LOGIN_MOBILE_WITH_TOKEN_FAILURE',

  // to submit user register with code
  REGISTER_WITH_OPTIONAL_PASS_REQUEST: 'REGISTER_WITH_OPTIONAL_PASS_REQUEST',
  REGISTER_WITH_OPTIONAL_PASS_SUCCESS: 'REGISTER_WITH_OPTIONAL_PASS_SUCCESS',
  REGISTER_WITH_OPTIONAL_PASS_FAILURE: 'REGISTER_WITH_OPTIONAL_PASS_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',
};
