export default {
  GET_ADVISERS_LIST_REQUEST: 'GET_ADVISERS_LIST_REQUEST',
  GET_ADVISERS_LIST_SUCCESS: 'GET_ADVISERS_LIST_SUCCESS',
  GET_ADVISERS_LIST_FAILURE: 'GET_ADVISERS_LIST_FAILURE',

  MAKE_VOIP_CALL_REQUEST: 'MAKE_VOIP_CALL_REQUEST',
  MAKE_VOIP_CALL_SUCCESS: 'MAKE_VOIP_CALL_SUCCESS',
  MAKE_VOIP_CALL_FAILURE: 'MAKE_VOIP_CALL_FAILURE',
};
