export default {
  INITIALIZE: 'INITIALIZE',
  INITIALIZE_FINISHED: 'INITIALIZE_FINISHED',
  LOADING: 'LOADING',
  FINISHED: 'FINISHED',
  CLEAR_CORE: 'CLEAR_CORE',

  SET_EXPERIMENTS: 'SET_EXPERIMENTS',
  SET_MAP_TYPE: 'SET_MAP_TYPE',
  PURGE_STORAGE: 'PURGE_STORAGE',

  QUEUE_ACTION: 'QUEUE_ACTION',
  QUEUE_ACTION_SUCCESS: 'QUEUE_ACTION_SUCCESS',
  QUEUE_ACTION_FAILURE: 'QUEUE_ACTION_FAILURE',
};
