export default {
  GET_CITIES_LIST_REQUEST: 'GET_CITIES_LIST_REQUEST',
  GET_CITIES_LIST_SUCCESS: 'GET_CITIES_LIST_SUCCESS',
  GET_CITIES_LIST_FAILURE: 'GET_CITIES_LIST_FAILURE',

  GET_PROVINCES_LIST_REQUEST: 'GET_PROVINCES_LIST_REQUEST',
  GET_PROVINCES_LIST_SUCCESS: 'GET_PROVINCES_LIST_SUCCESS',
  GET_PROVINCES_LIST_FAILURE: 'GET_PROVINCES_LIST_FAILURE',
};
