export default {
  GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
  OPEN_PRODUCT_MODAL: 'OPEN_PRODUCT_MODAL',
  CLOSE_PRODUCT_MODAL: 'CLOSE_PRODUCT_MODAL',
};
