version: '3.7'

services:
  pm2:
    build: .
    volumes:
      - ./node_modules:/home/node/node_modules
      - ./server:/home/node/server

  nginx_pwa:
    image: nginx:latest
    volumes:
      - ./build:/var/www/html
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 7777:80
