version: '3.7'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 9875:80
    volumes:
      - hackatourism_web_files:/var/www/html/
      - ./nginx:/etc/nginx/conf.d
volumes:
  hackatourism_web_files:
    name: hackatourism_web_files
