export default {
  SET_DEFAULT_LOCATION: 'SET_DEFAULT_LOCATION',

  REVERSE_GEO_CODER_REQUEST: 'REVERSE_GEO_CODER_REQUEST',
  REVERSE_GEO_CODER_SUCCESS: 'REVERSE_GEO_CODER_SUCCESS',
  REVERSE_GEO_CODER_FAILURE: 'REVERSE_GEO_CODER_FAILURE',

  SEARCH_LOCATION_REQUEST: 'SEARCH_LOCATION_REQUEST',
  SEARCH_LOCATION_SUCCESS: 'SEARCH_LOCATION_SUCCESS',
  SEARCH_LOCATION_FAILURE: 'SEARCH_LOCATION_FAILURE',
};
