export default {
  GET_CITIES_PATH_REQUEST: 'GET_CITIES_PATH_REQUEST',
  GET_CITIES_PATH_SUCCESS: 'GET_CITIES_PATH_SUCCESS',
  GET_CITIES_PATH_FAILURE: 'GET_CITIES_PATH_FAILURE',

  GET_AIRLINES_PATH_REQUEST: 'GET_AIRLINES_PATH_REQUEST',
  GET_AIRLINES_PATH_SUCCESS: 'GET_AIRLINES_PATH_SUCCESS',
  GET_AIRLINES_PATH_FAILURE: 'GET_AIRLINES_PATH_FAILURE',
};
