export default {
  APP_LOAD_REQUEST: 'APP_LOAD_REQUEST',
  APP_LOAD_SUCCESS: 'APP_LOAD_SUCCESS',
  APP_LOAD_FAILURE: 'APP_LOAD_FAILURE',

  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

  GET_ADDRESSES_REQUEST: 'GET_ADDRESSES_REQUEST',
  GET_ADDRESSES_SUCCESS: 'GET_ADDRESSES_SUCCESS',
  GET_ADDRESSES_FAILURE: 'GET_ADDRESSES_FAILURE',

  DELETE_ADDRESS_REQUEST: 'DELETE_ADDRESS_REQUEST',
  DELETE_ADDRESS_SUCCESS: 'DELETE_ADDRESS_SUCCESS',
  DELETE_ADDRESS_FAILURE: 'DELETE_ADDRESS_FAILURE',

  EDIT_ADDRESS_REQUEST: 'EDIT_ADDRESS_REQUEST',
  EDIT_ADDRESS_SUCCESS: 'EDIT_ADDRESS_SUCCESS',
  EDIT_ADDRESS_FAILURE: 'EDIT_ADDRESS_FAILURE',

  ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
  ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
  ADD_ADDRESS_FAILURE: 'ADD_ADDRESS_FAILURE',

  SET_PROFILE: 'SET_PROFILE',
  SET_SELECTED_ADDRESS: 'SET_SELECTED_ADDRESS',

  CLEAR_USER_DATA: 'CLEAR_USER_DATA',
};
